### ISSUE TITLE
Addition of package 'qfratio'?

### ISSUE THREAD

**Issue by watanabe-j** [cran-task-views/Distributions#28]
Dear task view maintainers,
I thought my package 'qfratio' ([CRAN](https://cran.r-project.org/package=qfratio); [GitHub](https://github.com/watanabe-j/qfratio)) might be of interest to the Distributions task view.
The package was originally developed for numerical evaluation of (compound) moments of ratios (and products) of quadratic forms in potentially noncentral normal variables using recursive algorithms, `qfrm()` and others. From a recent update (v1.1.0), it also involves density and distribution functions, `dqfr()` and `pqfr()` for this statistic. There is also a (rudimentary) random number generator `rqfr()` based on normal random variable generation. For technical details please see its README and two package vignettes.
There seems to be an existing package 'QF' which has a similar functionality, but that implementation is limited to the distribution function in the central case, `QF::pQF_depratio()`.

I would be glad to provide any further information. Thank you for your consideration.

**Comment by dutangc** [comment]
Dear pkg maintainer, I have just commited a new version. see the repo. Any comment is welcome. CD

**Comment by watanabe-j** [comment]
Thanks for your response. My package is named 'qfratio' and doesn't have any q function (yet).

And in my understanding 'QF' and 'Qapprox' primarily concern the distribution of quadratic forms rather than their ratios, although their p functions can be used as one for ratios and 'QF' has some functions dedicated to ratios. In this sense, these seem to align better with 'CompQuadForm' mentioned under "*Gaussian (or normal) distribution and its extensions*".
For these ones, I may be able to make a survey in the next few weeks and perhaps a pull request if that works.

**Comment by dutangc** [comment]
Ok Try a pull-request.

**Comment by watanabe-j** [comment]
Closed with #29. Thank you.
