### ISSUE TITLE
Please add documentation for conditional truncated multivariate normal distribution

### ISSUE THREAD

**Issue by phargarten2** [cran-task-views/Distributions#31]
Thank you for allowing the documentation of the packages to be in one place for easy use. To help users find the conditional truncated multivariate normal distribution, could you add the following?

Under "Multivariate Gaussian (or normal) distribution", and after "Finally, condMVNorm implements d, p, r functions for the conditional multivariate normal distribution.", please add:

> condTruncMVN https://cran.r-project.org/web/packages/condTruncMVN/index.html> implements d,p, r functions of the conditional truncated multivariate normal distribution. 

Thank you

**Comment by dutangc** [comment]
Thanks. Your package is added on the github version, soon on CRAN. CD

**Comment by phargarten2** [comment]
Thank you! I hope that this addition helps users find the distribution more easily.
