### ISSUE TITLE
Add StableEstim to the "Stable distribution" section

### ISSUE THREAD

**Issue by Beliavsky** [cran-task-views/Distributions#37]
https://cran.r-project.org/web/packages/StableEstim/index.html

StableEstim: Estimate the Four Parameters of Stable Laws using Different Methods

Estimate the four parameters of stable laws using maximum likelihood method, generalised method of moments with finite and continuum number of points, iterative Koutrouvelis regression and Kogon-McCulloch method. The asymptotic properties of the estimators (covariance matrix, confidence intervals) are also provided.

**Comment by dutangc** [comment]
Done by @swihart
